// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema_ranking.gtv.proto

package g_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//-----------------------------------------------------------------------------
// GTV_ranking_penalty_ticket_execute#cbf43926 ticker_execute_uuid:string user_ticket_uuid:Vector<string> = RankingPenaltyTicketExecute;
type GTVRankingPenaltyTicketExecute struct {
	TickerExecuteUuid    string   `protobuf:"bytes,1,opt,name=ticker_execute_uuid,json=tickerExecuteUuid,proto3" json:"ticker_execute_uuid,omitempty"`
	UserTicketUuid       []string `protobuf:"bytes,2,rep,name=user_ticket_uuid,json=userTicketUuid,proto3" json:"user_ticket_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GTVRankingPenaltyTicketExecute) Reset()         { *m = GTVRankingPenaltyTicketExecute{} }
func (m *GTVRankingPenaltyTicketExecute) String() string { return proto.CompactTextString(m) }
func (*GTVRankingPenaltyTicketExecute) ProtoMessage()    {}
func (*GTVRankingPenaltyTicketExecute) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3af10c71899c376, []int{0}
}

func (m *GTVRankingPenaltyTicketExecute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GTVRankingPenaltyTicketExecute.Unmarshal(m, b)
}
func (m *GTVRankingPenaltyTicketExecute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GTVRankingPenaltyTicketExecute.Marshal(b, m, deterministic)
}
func (m *GTVRankingPenaltyTicketExecute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GTVRankingPenaltyTicketExecute.Merge(m, src)
}
func (m *GTVRankingPenaltyTicketExecute) XXX_Size() int {
	return xxx_messageInfo_GTVRankingPenaltyTicketExecute.Size(m)
}
func (m *GTVRankingPenaltyTicketExecute) XXX_DiscardUnknown() {
	xxx_messageInfo_GTVRankingPenaltyTicketExecute.DiscardUnknown(m)
}

var xxx_messageInfo_GTVRankingPenaltyTicketExecute proto.InternalMessageInfo

func (m *GTVRankingPenaltyTicketExecute) GetTickerExecuteUuid() string {
	if m != nil {
		return m.TickerExecuteUuid
	}
	return ""
}

func (m *GTVRankingPenaltyTicketExecute) GetUserTicketUuid() []string {
	if m != nil {
		return m.UserTicketUuid
	}
	return nil
}

func init() {
	proto.RegisterType((*GTVRankingPenaltyTicketExecute)(nil), "g_proto.GTV_ranking_penalty_ticket_execute")
}

func init() { proto.RegisterFile("schema_ranking.gtv.proto", fileDescriptor_e3af10c71899c376) }

var fileDescriptor_e3af10c71899c376 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4e, 0xce, 0x48,
	0xcd, 0x4d, 0x8c, 0x2f, 0x4a, 0xcc, 0xcb, 0xce, 0xcc, 0x4b, 0xd7, 0x4b, 0x2f, 0x29, 0xd3, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x8f, 0x07, 0x33, 0x94, 0xea, 0xb8, 0x94, 0xdc, 0x43,
	0xc2, 0x60, 0x2a, 0xe2, 0x0b, 0x52, 0xf3, 0x12, 0x73, 0x4a, 0x2a, 0xe3, 0x4b, 0x32, 0x93, 0xb3,
	0x53, 0x4b, 0xe2, 0x53, 0x2b, 0x52, 0x93, 0x4b, 0x4b, 0x52, 0x85, 0xf4, 0xb8, 0x84, 0xc1, 0x22,
	0x45, 0x30, 0x91, 0xf8, 0xd2, 0xd2, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x41,
	0x88, 0x94, 0x2b, 0x44, 0x26, 0xb4, 0x34, 0x33, 0x45, 0x48, 0x83, 0x4b, 0xa0, 0xb4, 0x38, 0xb5,
	0x08, 0x66, 0x0c, 0x58, 0x31, 0x93, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x1f, 0x48, 0x3c, 0x04, 0x2c,
	0x0c, 0x52, 0xe9, 0x24, 0xcd, 0xc5, 0x57, 0x96, 0x07, 0x76, 0x18, 0xd4, 0x45, 0x4e, 0xec, 0xee,
	0xf1, 0x01, 0x20, 0x86, 0x07, 0x53, 0x12, 0x1b, 0x58, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xd5, 0xf6, 0xaa, 0xb9, 0xc8, 0x00, 0x00, 0x00,
}
